language: cpp

services:
  - docker

cache:
  ccache: true

env:
  global:
    - CCACHE_DIR=$HOME/.ccache
    - PX4_DOCKER_REPO=px4io/px4-dev-ros:2018-04-22
    - BUILD_WITH_CMAKE = "mkdir Build; cd Build; cmake ..; make"
    - BUILD_WITH_CATKIN = "source /opt/ros/kinetic/setup.bash; mkdir -p ~/catkin_ws/src; cd ~/catkin_ws/src; catkin_init_workspace; ln -s ${TRAVIS_BUILD_DIR} .; cd ~/catkin_ws; catkin_make"
    - VALIDATE_SDF_SCHEMAS = "source ./scripts/validate_sdf.bash"

  matrix:
    # Cmake build
    - STEP=${BUILD_WITH_CMAKE}
    # Catkin build
    - STEP=${BUILD_WITH_CATKIN}
    # Validate SDF schemas
    - STEP=${VALIDATE_SDF_SCHEMAS}

script:
  - docker run -it --rm -w ${TRAVIS_BUILD_DIR} --env=CCACHE_DIR="${CCACHE_DIR}" --env=LOCAL_USER_ID="$(id -u)" --volume=${CCACHE_DIR}:${CCACHE_DIR}:rw --volume=${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR}:rw ${PX4_DOCKER_REPO} /bin/bash -e -c "${STEP}"
