name: MacOS Build Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11.0]
    steps:
    - uses: actions/checkout@v1
    - name: submodule update
      run: git submodule update --init --recursive
    - name: Before Install
      run: |
        brew update;
        git clone -b release-1.10.0 https://github.com/google/googletest
        git clone https://github.com/mavlink/c_library_v2.git /usr/local/include/mavlink/v2.0
    - name: Checkout Firmware master
      uses: actions/checkout@v2.3.1
      with:
        repository: PX4/Firmware
        ref: master
        path: Firmware
        fetch-depth: 0
        submodules: recurvise
    - name: Install
      working-directory: Firmware
      run: ./Tools/setup/macos.sh; ./Tools/setup/macos.sh
    - name: Cmake Build
      working-directory:
      run: |
        mkdir build
        cd build
        cmake ..
        make
    - name: Unit Tests
      working-directory: build
      run: |
        cmake -DENABLE_UNIT_TESTS=On ..
        make
        make test
